name: Deploy Modifier to ECR

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: modifier-repo
  IMAGE_TAG: ${{ github.sha }}
  KEEP_LAST_IMAGES: 2  #  保留最近2个镜像

jobs:
  deploy-modifier:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build backend Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
                       -t ${{ env.ECR_REPOSITORY }}:latest .

      - name: Tag and push backend image
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          docker tag ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.ECR_REPOSITORY }}:latest $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest

      - name: Cleanup old images
        run: |
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          REPO_NAME=${{ env.ECR_REPOSITORY }}
          
          # 获取所有镜像并按推送时间排序（排除 latest 标签）
          IMAGE_TAGS=$(aws ecr describe-images --repository-name $REPO_NAME \
            --query 'sort_by(imageDetails, &imagePushedAt)[*].imageTags' \
            --output text | tr '\t' '\n' | grep -v "latest" | sort -u)
          
          TOTAL_IMAGES=$(echo "$IMAGE_TAGS" | wc -l)
          IMAGES_TO_DELETE=$((TOTAL_IMAGES - ${{ env.KEEP_LAST_IMAGES }}))
          
          if [ $IMAGES_TO_DELETE -gt 0 ]; then
            echo "Deleting $IMAGES_TO_DELETE old images"
            OLD_TAGS=$(echo "$IMAGE_TAGS" | head -n $IMAGES_TO_DELETE)
            for TAG in $OLD_TAGS; do
              aws ecr batch-delete-image \
                --repository-name $REPO_NAME \
                --image-ids imageTag=$TAG
            done
          else
            echo "No images to delete"
          fi
